Document: tengine
Title: Debian tengine Manual
Author: <betterpm@gmail.com>
Abstract: This manual describes what tengine is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /opt/share/doc/tengine/tengine.sgml.gz

Format: postscript
Files: /opt/share/doc/tengine/tengine.ps.gz

Format: text
Files: /opt/share/doc/tengine/tengine.text.gz

Format: HTML
Index: /opt/share/doc/tengine/html/index.html
Files: /opt/share/doc/tengine/html/*.html
